### PR TITLE
Fix for off-by-one precision radius

### PR DESCRIPTION
**Pull request by afairclo**

### CODE REVIEW

**Comment by brianshea2** [comment]
```javascript
for (let i = 1; i <= 32; i++) {
    console.log(i, Math.round(map.distance(
        [0xffffffff / 10000000, 0],
        [parseInt(`${'1'.repeat(i)}${'0'.repeat(32-i)}`, 2) / 10000000, 0]
    )))
}
```
```
1 16151245
2 11939464
3 5969732
4 2984866
5 1492433
6 746217
7 373108
8 186554
9 93277
10 46639
11 23319
12 11660
13 5830
14 2915
15 1457
16 729
17 364
18 182
19 91
20 46
21 23
22 11
23 6
24 3
25 1
26 1
27 0
28 0
29 0
30 0
31 0
32 0
```

**Comment by brianshea2** [comment]
First, thank you for finding this issue and providing a fix!

Just for reference and my own notes, the above is how I calculated the distances originally, using the same leafletjs library the website uses.

The distances used by the app are similar but seem to be off by one bit place themselves? (ref: [Channels.swift](https://github.com/meshtastic/Meshtastic-Apple/blob/4b3407ce7262389229ccb066405c275aa0e2ccff/Meshtastic/Views/Settings/Channels.swift#L337) -- thanks for the link) Or maybe they aren't counting the first bit since that's the sign bit and so are only considering 31 bits of precision. Whatever the reasoning, I do believe the map should match the app, so this is a welcome change.

Small nitpick, would you mind rearranging the array to make all lines have the same number of elements again?

**Comment by afairclo** [comment]
I think I did that right. First commit to someone else's stuff.

**Comment by brianshea2** [comment]
Thank you!

**Review by brianshea2 — APPROVED** [review]

**Pull request merged**
